### ISSUE TITLE
【提案】UIを曲げて表示することは可能ですか？

### ISSUE THREAD

**Issue by ricktsukida** [nuhs/vrws0127#2]
現状のUIは平面をそのまま画面上に出力していますが、
これをVR上で見やすいように、少し曲げた（円弧状）感じに配置することは可能ですか？
実装が可能なら。レベルの高い人向けのオプション実装項目として用意出来ればと考えます。
参考URL＞http://tips.hecomi.com/?page=1482504118

**Comment by nuhs** [comment]
ShaderLab でゴニョゴニョしないとダメだと思うのですが、
ちょっとそこら辺については疎いので難しそうです。
ただ個人的に興味はあったので下記リンク先の unity package を参考に試してみたのですが
ugui の Text は曲げられても Button (というか Plane?) が曲げられず詰まりました。。
https://forum.unity3d.com/threads/warp-bend-the-ui.283066/#post-1886153

普段触ってる OpenGL でやろうと思うと更に難しくなりそうな感触です。

**Comment by ricktsukida** [comment]
これとか参考になりませんかね。

https://github.com/googlevr/gvr-unity-sdk/blob/master/Samples/CardboardDesignLab/ustwo-cardboard-unity/Assets/CurvedUI/Shaders/UI-Cylinder.shader

**Comment by ricktsukida** [comment]
もしそれでも難しそうなら大丈夫です。

**Comment by nuhs** [comment]
参考リンクありがとうございます。
今試しに差し替えて検証してみましたがダメそうでした。。

**Comment by ricktsukida** [comment]
かしこまりました。ではこの機能は無しにします。
