### ISSUE TITLE
【Question】使用している素材やスクリプトの権利について

### ISSUE THREAD

**Issue by ricktsukida** [nuhs/vrws0127#4]
このプロジェクトで使われている素材やスクリプトで、外に漏らしてはいけない（受講者が講座内容をネットに乗せるなど）など、そういったものがあれば教えてください。

**Comment by nuhs** [comment]
特にそういったものはございません。

**Comment by ricktsukida** [comment]
かしこまりました。ありがとうございます。
こちらの質問は閉じさせていただきます。
